version: '3'
services:
  db:
    image: postgres:11-alpine
    expose:
      - "5432"
    networks:
      - nestjs_example_network
    container_name: nestjs_example-db
    restart: always

  redis:
    image: redis:5.0.7-alpine
    expose:
      - "6379"
    networks:
      - nestjs_example_network
    container_name: nestjs_example-redis
    restart: always

  beta-web:
    build:
      context: .
      args:
        - env=development
    #image: 
    ports:
      - '8080:80'
      - '8081:80'
      # - '$EXTERNAL:$INTERNAL'
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - nestjs_example_network
    container_name: nestjs_example-web
    volumes:
      - ./uploads:/server/uploads

networks:
  nestjs_example_network:
    external: true
